version: '3.7'
services:
  nginx:
    image: xandurx/ofbiz-proxy:1.0.1-SNAPSHOT
    ports:
      - "80:80"
    networks:
      webnet:
        aliases:
          - ng

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ofbiz
      POSTGRES_USER: ofbiz
      POSTGRES_PASSWORD: ofbiz
    depends_on:
      - nginx
    ports:
      - "5432:5432"
    networks:
      webnet:
        aliases:
          - pg

  ofbiz:
    depends_on:
      - postgres
    image: xandurx/ofbiz-backend:1.0.1-SNAPSHOT
    ports:
      - "8443:8443"
    networks:
      webnet:
        aliases:
          - ofbiz

networks:
  webnet:
